export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
          "surface-container-high": "#e6e9e7",
          "primary": "#186a22",
          "on-primary-container": "#f7fff1",
          "on-primary-fixed-variant": "#005312",
          "primary-fixed-dim": "#88d982",
          "surface-container-highest": "#e1e3e1",
          "inverse-surface": "#2e3130",
          "tertiary": "#765700",
          "secondary-container": "#fed7ca",
          "surface-container": "#eceeec",
          "on-secondary-fixed": "#2b160f",
          "on-surface": "#191c1b",
          "error-container": "#ffdad6",
          "on-primary-fixed": "#002204",
          "tertiary-container": "#956e00",
          "on-secondary": "#ffffff",
          "surface-bright": "#f8faf8",
          "on-tertiary-container": "#fffbff",
          "surface-container-low": "#f2f4f2",
          "surface-variant": "#e1e3e1",
          "primary-container": "#358438",
          "secondary": "#75584d",
          "error": "#ba1a1a",
          "secondary-fixed-dim": "#e4beb2",
          "on-background": "#191c1b",
          "surface": "#f8faf8",
          "inverse-primary": "#88d982",
          "on-surface-variant": "#3f4a3d",
          "outline-variant": "#bfcab9",
          "tertiary-fixed": "#ffdfa0",
          "inverse-on-surface": "#eff1ef",
          "primary-fixed": "#a3f69c",
          "surface-tint": "#1b6d24",
          "on-tertiary": "#ffffff",
          "on-tertiary-fixed": "#261a00",
          "on-secondary-fixed-variant": "#5b4137",
          "on-tertiary-fixed-variant": "#5c4300",
          "surface-container-lowest": "#ffffff",
          "on-error": "#ffffff",
          "tertiary-fixed-dim": "#f8bd2a",
          "outline": "#6f7a6b",
          "surface-dim": "#d8dad9",
          "on-error-container": "#93000a",
          "secondary-fixed": "#ffdbce",
          "on-secondary-container": "#795c51",
          "on-primary": "#ffffff",
          "background": "#f8faf8"
      },
      "borderRadius": {
          "DEFAULT": "1rem",
          "lg": "2rem",
          "xl": "3rem",
          "full": "9999px"
      },
      "fontFamily": {
          "headline": ["Plus Jakarta Sans"],
          "body": ["Inter"],
          "label": ["Inter"]
      }
    },
  },
  plugins: [],
}
